### ISSUE TITLE
希望官方制作release版本或制作安装教程

### ISSUE THREAD

**Issue by deepcola** [nebulasio/nr-service#1]
安装时遇到诸多麻烦，尤其是arangodb的C++驱动，编译了几次都无法通过，也没有详细的说明文件等等，希望官方推出一个安装教程。

**Comment by xchmwang** [comment]
最近会出安装教程

**Comment by xchmwang** [comment]
已更新安装教程

**Comment by deepcola** [comment]
> 已更新安装教程

感谢官方的辛苦付出，编译已经完成
---------------------------
1.运行 ./prepare.sh 提示找不到若干CMkaeLists.txt文件（尝试git clone --recursive https://github.com/nebulasio/nr-service.git 一次性clone所有子模块解决）
2. 运行./prepare.sh提示找不到OPENSSL云云（编译安装openssl解决，git clone   /config make make test make install）
3.env.set.sh 中的环境变量 export DB_URL=不知如何填写（填写tcp://localhost:8529解决）
4.编译NR服务提示找不到CMakeLists.txt（在cpp而不是项目根目录下 mkdir build解决）
5.编译过程中提示如下错误信息（问题已解决，是由于依赖项目没有正确安装导致）
